In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('Advertising.csv')
df.head()

       TV  radio  newspaper  sales
0  230100  37800      69200  22100
1   44500  39300      45100  10400
2   17200  45900      69300   9300
3  151500  41300      58500  18500
4  180800  10800      58400  12900

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    int64
 1   radio      200 non-null    int64
 2   newspaper  200 non-null    int64
 3   sales      200 non-null    int64
dtypes: int64(4)
memory usage: 6.4 KB

#### **Eploratory Data Analysis**

In [4]:
df.describe()

                  TV         radio      newspaper         sales
count     200.000000    200.000000     200.000000    200.000000
mean   147042.500000  23264.000000   30554.000000  14022.500000
std     85854.236315  14846.809176   21778.620839   5217.456566
min       700.000000      0.000000     300.000000   1600.000000
25%     74375.000000   9975.000000   12750.000000  10375.000000
50%    149750.000000  22900.000000   25750.000000  12900.000000
75%    218825.000000  36525.000000   45100.000000  17400.000000
max    296400.000000  49600.000000  114000.000000  27000.000000

In [5]:
df.corr()

                 TV     radio  newspaper     sales
TV         1.000000  0.054809   0.056648  0.782224
radio      0.054809  1.000000   0.354104  0.576223
newspaper  0.056648  0.354104   1.000000  0.228299
sales      0.782224  0.576223   0.228299  1.000000

In [13]:
X = df.drop(columns='sales')
y = df['sales']

In [15]:
from sklearn.model_selection import train_test_split

X_train , X_test, y_train, y_test = train_test_split(X,y, test_size=  0.3, random_state=42)

## **Lasso Regression**

**Modeling with default parameters**

In [16]:
from sklearn.linear_model import Lasso         # import

lasso_model = Lasso()                          # save as a model name

lasso_model.fit(X_train, y_train)              # fit on train data

Lasso()

**Prediction**

In [17]:
test_predictions = lasso_model.predict(X_test)
train_predictions = lasso_model.predict(X_train)

**Evaluation**

In [18]:
from sklearn.metrics import mean_squared_error
train_rmse = np.sqrt(mean_squared_error(y_train, train_predictions))
test_rmse = np.sqrt(mean_squared_error(y_test, test_predictions))

print('train RMSE : ', train_rmse)
print('test RMSE : ', test_rmse)

train RMSE :  1574.596830590546
test RMSE :  1948.5371732825658

#### **Hyperparameter tuning**

In [19]:
from sklearn.model_selection import GridSearchCV

In [21]:
estimator = Lasso()

param_grid = {'alpha': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1]}

In [22]:
model_hp = GridSearchCV(estimator, param_grid, cv = 5)
model_hp.fit(X_train, y_train)
model_hp.best_params_

{'alpha': 1}

## **Ridge Regresssion**

**Modeling with default parameters**

In [24]:
from sklearn.linear_model import Ridge


ridge_model  = Ridge()

ridge_model.fit(X_train, y_train)

Ridge()

In [28]:
test_predictions = ridge_model.predict(X_test)
train_predictions = ridge_model.predict(X_train)

**Evaluation**

In [29]:
from sklearn.metrics import mean_squared_error
train_rmse = np.sqrt(mean_squared_error(y_train, train_predictions))
test_rmse = np.sqrt(mean_squared_error(y_test, test_predictions))

print('train RMSE : ', train_rmse)
print('test RMSE : ', test_rmse)

train RMSE :  1574.5968305905444
test RMSE :  1948.5372043175973

## **Hyperparameter Tunig**
**Identifying the best alpha value for Ridge Regression**

In [30]:
from sklearn.model_selection import GridSearchCV

In [31]:
estimator = Ridge()
param_grid = {'alpha':list(range(1,11))}

In [32]:
model_hp = GridSearchCV(estimator, param_grid, cv=5)
model_hp.fit(X_train, y_train)
model_hp.best_params_

{'alpha': 10}

## **Elasticnet Regression**

**Modeling with default parameters**

In [33]:
from sklearn.linear_model import ElasticNet

elr_model = ElasticNet()

elr_model.fit(X_train, y_train)

ElasticNet()

**Prediction**

In [34]:
test_predictions = elr_model.predict(X_test)
train_predictions = elr_model.predict(X_train)

**Evaluation**

In [35]:
from sklearn.metrics import  mean_squared_error

train_rmse = np.sqrt(mean_squared_error(y_train, train_predictions))
test_rmse = np.sqrt(mean_squared_error(y_test, test_predictions ))

#### **Hyperparameter tuning**

In [36]:
from sklearn.model_selection import GridSearchCV

In [37]:
estimator = ElasticNet()
param_grid = {'alpha': [0.1, 0.2, 1, 2, 3, 5, 10],
            'l1_ratio':[0.1, 0.5, 0.75, 0.9, 0.95, 1]}

In [38]:
enr_hp = GridSearchCV(estimator, param_grid, cv = 5)
enr_hp.fit(X_train, y_train)
enr_hp.best_params_

{'alpha': 10, 'l1_ratio': 1}