## Feature Preprocessing : Tranformation

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('titanic.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
data = pd.read_csv('titanic.csv', usecols=['Fare'])
data.head()

      Fare
0   7.2500
1  71.2833
2   7.9250
3  53.1000
4   8.0500

In [4]:
data.Fare.skew()

np.float64(4.787316519674893)

## Root Transformation

In [5]:
data['sqr_Fare'] = data.Fare **(1/4)
data.sqr_Fare.skew()

np.float64(0.5196788882063811)

## Logarithmi Transformation

In [6]:
data['Log_Fare'] = np.log(data.Fare + 0.01)
data.Log_Fare.skew()

np.float64(-2.4100496984507678)

## Reciprocal Transformation

In [7]:
data['Rec_Fare'] = 1/ (data.Fare + 0.01) 
data.Rec_Fare.skew()

np.float64(7.523650082079874)

## BoxCox

The Box-Cox transformation is defined as:

(X**λ -1)/λ

where X is the response variable and λ is the tranformation parameter. λ variable from the transformation, all values of λ are consider and the optimal  value for a given variable selected.

In [8]:
from scipy import stats

In [9]:
# transform training data & save Lambda value
data['Fare_boxcox'], param = stats.boxcox(data.Fare + 0.01)

In [10]:
print('λ = ', param)

λ =  0.18091321955492742

In [11]:
data.Fare_boxcox.skew()

np.float64(0.2528246123555105)