In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
data = pd.read_csv('penguins_size.csv')
data.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [23]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   culmen_length_mm   342 non-null    float64
 3   culmen_depth_mm    342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    str
dtypes: float64(4), str(3)
memory usage: 24.9 KB

In [24]:
data.species.value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [25]:
data.species.unique()

<ArrowStringArray>
['Adelie', 'Chinstrap', 'Gentoo']
Length: 3, dtype: str

In [26]:
data.species = data.species.replace({
    'Adelie':0,
    'Chinstrap':1,
    'Gentoo':2
}).astype('int')

In [27]:
data.island.unique()

<ArrowStringArray>
['Torgersen', 'Biscoe', 'Dream']
Length: 3, dtype: str

In [28]:
data.island = data.island.replace({
    'Torgersen':2, 'Biscoe':0, 'Dream':1
}).astype('int')

In [29]:
data.sex.unique()

<ArrowStringArray>
['MALE', 'FEMALE', nan, '.']
Length: 4, dtype: str

In [33]:
data = data[data.sex != '.']

In [39]:
data.sex.unique()

array([1, 0])

In [35]:
data.sex = data.sex.fillna(data.sex.mode()[0])

In [38]:
data.sex = data.sex.replace({
    'MALE':1,
    'FEMALE':0
}).astype('int')

In [44]:
data.isnull().sum()

species              0
island               0
culmen_length_mm     0
culmen_depth_mm      0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [41]:
data.culmen_length_mm = data.culmen_length_mm.fillna(data.culmen_length_mm.mean())
data.culmen_depth_mm  = data.culmen_depth_mm.fillna(data.culmen_depth_mm.mean())   
data.flipper_length_mm = data.flipper_length_mm.fillna(data.flipper_length_mm.mean())

In [43]:
data.body_mass_g = data.body_mass_g.fillna(data.body_mass_g.mean())

In [46]:
pd.crosstab(data['species'],data['island'],margins = True)

island     0    1   2  All
species
0         44   56  52  152
1          0   68   0   68
2        123    0   0  123
All      167  124  52  343

In [47]:
pd.crosstab(data['species'],data['sex'],margins = True)

sex        0    1  All
species
0         73   79  152
1         34   34   68
2         58   65  123
All      165  178  343

In [48]:
data.describe()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
count,343.000000,343.000000,343.000000,343.000000,343.000000,343.000000,343.000000
mean,0.915452,0.664723,43.920235,17.155425,200.868035,4199.780059,0.518950
std,0.892706,0.726369,5.451506,1.970337,14.014097,799.950855,0.500371
min,0.000000,0.000000,32.100000,13.100000,172.000000,2700.000000,0.000000
25%,0.000000,0.000000,39.250000,15.600000,190.000000,3550.000000,0.000000
50%,1.000000,1.000000,44.100000,17.300000,197.000000,4050.000000,1.000000
75%,2.000000,1.000000,48.500000,18.700000,213.000000,4750.000000,1.000000
max,2.000000,2.000000,59.600000,21.500000,231.000000,6300.000000,1.000000

## **encoding**

In [49]:
pd.get_dummies(data.drop('species', axis = 1), drop_first=True)

,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,2,39.100000,18.700000,181.000000,3750.000000,1
1,2,39.500000,17.400000,186.000000,3800.000000,0
2,2,40.300000,18.000000,195.000000,3250.000000,0
3,2,43.920235,17.155425,200.868035,4199.780059,1
4,2,36.700000,19.300000,193.000000,3450.000000,0
...,...,...,...,...,...,...
339,0,43.920235,17.155425,200.868035,4199.780059,1
340,0,46.800000,14.300000,215.000000,4850.000000,0
341,0,50.400000,15.700000,222.000000,5750.000000,1
342,0,45.200000,14.800000,212.000000,5200.000000,0
343,0,49.900000,16.100000,213.000000,5400.000000,1

In [50]:
X = data.drop('species', axis = 1)
y = data['species']

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=101, test_size=0.3)

from sklearn.ensemble import RandomForestClassifier

dtc = RandomForestClassifier(random_state=42)
dtc.fit(X_train, y_train)

train_pred = dtc.predict(X_train)
test_pred = dtc.predict(X_test)

# accuracy

from sklearn.metrics import accuracy_score
print(accuracy_score(y_train,train_pred))
print(accuracy_score(y_test,test_pred))


# cross validation score

from sklearn.model_selection import cross_val_score

score = cross_val_score(dtc, X, y, cv= 5)
print(score)

print(score.mean())

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, test_pred))

1.0
0.9805825242718447
[1.         1.         0.98550725 1.         0.97058824]
0.9912190963341858
[[41  0  0]
 [ 2 25  0]
 [ 0  0 35]]

In [59]:
from sklearn.metrics import classification_report

print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.98        41
           1       1.00      0.93      0.96        27
           2       1.00      1.00      1.00        35

    accuracy                           0.98       103
   macro avg       0.98      0.98      0.98       103
weighted avg       0.98      0.98      0.98       103

In [60]:
dtc.feature_importances_

array([0.10822609, 0.35986382, 0.1423457 , 0.25689536, 0.12457679,
       0.00809224])

In [61]:
pd.DataFrame(index = X.columns,
             data = dtc.feature_importances_,
             columns=['feature importance'])

                   feature importance
island                       0.108226
culmen_length_mm             0.359864
culmen_depth_mm              0.142346
flipper_length_mm            0.256895
body_mass_g                  0.124577
sex                          0.008092

## **Hyperparameter tuning**

In [66]:
from sklearn.model_selection import GridSearchCV

estimator = RandomForestClassifier(random_state=101 , bootstrap=False)
param_grid = {'n_estimators':list(range(1,10))}

Hp_rfc = GridSearchCV(estimator, param_grid, cv= 5, scoring='accuracy')

Hp_rfc.fit(X_train, y_train)

Hp_rfc.best_params_

{'n_estimators': 5}

## **Rebuild the final model**

In [67]:
rtc = RandomForestClassifier(n_estimators = 5, bootstrap=False)
rtc.fit(X_train, y_train)

train_pred = dtc.predict(X_train)
test_pred = dtc.predict(X_test)

print('Train accuracy:' , accuracy_score(y_train,train_pred))
print('Test accuracy:' , accuracy_score(y_test,test_pred))

score= cross_val_score(dtc,X,y,cv=5)
print(score)
score.mean()

Train accuracy: 1.0
Test accuracy: 0.9805825242718447
[1.         1.         0.98550725 1.         0.97058824]

np.float64(0.9912190963341858)