In [7]:
data = [['milk', 'bread','rice','book'],
        ['bread','jam','book','pen'],
        ['jam','milk','bread','rice','eggs'],
        ['rice','eggs','pen','book'],
        ['eggs','pen','milk','bread','jam'],
        ['eggs','rice','bread','jam']
]


data

[['milk', 'bread', 'rice', 'book'],
 ['bread', 'jam', 'book', 'pen'],
 ['jam', 'milk', 'bread', 'rice', 'eggs'],
 ['rice', 'eggs', 'pen', 'book'],
 ['eggs', 'pen', 'milk', 'bread', 'jam'],
 ['eggs', 'rice', 'bread', 'jam']]

In [8]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()

te_array = te.fit_transform(data)

In [9]:
import pandas as pd
df = pd.DataFrame(te_array, columns = te.columns_)
df

    book  bread   eggs    jam   milk    pen   rice
0   True   True  False  False   True  False   True
1   True   True  False   True  False   True  False
2  False   True   True   True   True  False   True
3   True  False   True  False  False   True   True
4  False   True   True   True   True   True  False
5  False   True   True   True  False  False   True

In [10]:
from mlxtend.frequent_patterns import apriori
itemset = apriori(df, min_support = 0.6, use_colnames=True)
itemset

    support                 itemsets
0  0.833333       frozenset({bread})
1  0.666667        frozenset({eggs})
2  0.666667         frozenset({jam})
3  0.666667        frozenset({rice})
4  0.666667  frozenset({bread, jam})

In [11]:
from mlxtend.frequent_patterns import association_rules
res = association_rules(itemset, metric='confidence', min_threshold=0.6)
res

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({bread}),frozenset({jam}),0.833333,0.666667,0.666667,0.8,1.2,1.0,0.111111,1.666667,1.0,0.8,0.4,0.9
1,frozenset({jam}),frozenset({bread}),0.666667,0.833333,0.666667,1.0,1.2,1.0,0.111111,inf,0.5,0.8,1.0,0.9

In [12]:
result = res[['antecedents','consequents','support','confidence','lift']]
result

          antecedents         consequents   support  confidence  lift
0  frozenset({bread})    frozenset({jam})  0.666667         0.8   1.2
1    frozenset({jam})  frozenset({bread})  0.666667         1.0   1.2