In [22]:
import pandas as pd

In [23]:
df = pd.read_excel('C:\\Users\\abhay\\OneDrive\\Desktop\\Data_Science_Advance\\Data_Science_Advance\\DS_2_Python_For_Data_Science\\liver.xlsx')
df.head()

   Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0   65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1   62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2   62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3   58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4   72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1

## Sum

In [24]:
df['Age'].sum()

np.int64(26087)

## Mean

In [25]:
df['Age'].mean()

np.float64(44.74614065180103)

## Median

In [26]:
df['Age'].median()

45.0

## Mode

In [27]:
df.Age.mode()

0    60
Name: Age, dtype: int64

## Min

In [28]:
df.Age.min()

4

## Max

In [29]:
df.Age.max()

90

## Quartiles

In [30]:
# 25 percentile of Q1

df.Age.quantile(0.25)

np.float64(33.0)

In [31]:
# 75 percentile or Q3
df.Age.quantile(0.75)

np.float64(58.0)

## Overall Descriptive Statistics

In [32]:
df.describe()

,Age,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
count,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,579.000000,583.000000
mean,44.746141,3.298799,1.486106,290.576329,80.713551,109.910806,6.483190,3.141852,0.947064,0.713551
std,16.189833,6.209522,2.808498,242.937989,182.620356,288.918529,1.085451,0.795519,0.319592,0.452490
min,4.000000,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000,0.000000
25%,33.000000,0.800000,0.200000,175.500000,23.000000,25.000000,5.800000,2.600000,0.700000,0.000000
50%,45.000000,1.000000,0.300000,208.000000,35.000000,42.000000,6.600000,3.100000,0.930000,1.000000
75%,58.000000,2.600000,1.300000,298.000000,60.500000,87.000000,7.200000,3.800000,1.100000,1.000000
max,90.000000,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000,1.000000

In [33]:
df.describe(include='all')

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,AG,LiverPatient
count,583.000000,583,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,579.000000,583.000000
unique,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,44.746141,NaN,3.298799,1.486106,290.576329,80.713551,109.910806,6.483190,3.141852,0.947064,0.713551
std,16.189833,NaN,6.209522,2.808498,242.937989,182.620356,288.918529,1.085451,0.795519,0.319592,0.452490
min,4.000000,NaN,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000,0.000000
25%,33.000000,NaN,0.800000,0.200000,175.500000,23.000000,25.000000,5.800000,2.600000,0.700000,0.000000
50%,45.000000,NaN,1.000000,0.300000,208.000000,35.000000,42.000000,6.600000,3.100000,0.930000,1.000000
75%,58.000000,NaN,2.600000,1.300000,298.000000,60.500000,87.000000,7.200000,3.800000,1.100000,1.000000
max,90.000000,NaN,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000,1.000000

## Range

In [34]:
def range_cal(data):
    min_val = min(data)
    max_val = max(data)
    return (max_val - min_val)

range_cal(df.Age)

86

## Percentile

In [35]:
# 10 percentile
df.Age.quantile(0.1)

np.float64(23.0)

## Skewness

- If skewness = 0, then it is called as perfect normal distribution
- If skewness value lies between -1 to +1 --- normal distribution
- If skewness < -1, then it is left skewed
- If skewness > +1, then it is right skewed

In [36]:
df.Age.skew()

np.float64(-0.029385312710346265)

## Kurtosis

In [37]:
df.Age.kurt()

np.float64(-0.5600656409430136)